# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e9172f765b87ef0b26ecd9543c1cf9aa1673e745f58da668d48388129a7ba16d807012125b102515027afee213521c188bf9db6e89af59099eb68babca22310d

test:
  secret_key_base: efa1070ae1f0a220337150952bbdbd9192589d810ebd1300eba8987c665798c2554c8535f841ea4f0e466d80b99574301da6f1b44554f3e22b36a48edb1d3cf8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
